server:
  port: 9000
spring:
  application:
    name: service-web
  datasource:
    url: jdbc:postgresql://localhost:5432/db_micropayment
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  activemq:
    packages:
      trust-all: true
    broker-url: failover://tcp://localhost:61616
    user: admin
    password: admin
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://localhost:1000}/eureka/
      
micropayment:
  queue: micropayment.queue