server:
  port: 9000
spring:
  application:
    name: service-web
  activemq:
    packages:
      trust-all: true
    broker-url: failover://tcp://localhost:61616
    user: admin
    password: admin
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://localhost:1000}/eureka/
      
micropayment:
  queue: micropayment.queue
client:
  host: http://localhost:3000