server:
  port: 3000
  
spring:
  application:
    name: service-core
    
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://localhost:1000}/eureka/